[package]
name = "ranbo"
version = "0.1.0"
authors = ["Jon Carr <jec@joncarr.xyz>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
color-thief = "0.1.0"
image = "0.21.0"
# color_processing = "0.2.0"
# bart = "0.1.4"
# bart_derive = "0.1.4"
# handlebars = "1.1.0"
