;; base16-ranbo-theme.el -- A base16 color scheme generated by ranbo

;;; Commentary:
;; Base16 Ranbo

;;; Authors:
;; Scheme: Generated from an image by Ranbo
;; Template: Kaleb Elwert <belak@coded.io>

;;; Code:

(require 'base16-theme)

(defvar base16-ranbo-colors
  '(:base00 "{color0}"
    :base01 "{color1}"
    :base02 "{color2}"
    :base03 "{color3}"
    :base04 "{color5}"
    :base05 "{color4}"
    :base06 "{color6}"
    :base07 "{color7}"
    :base08 "{color8}"
    :base09 "{color9}"
    :base0A "{color10}"
    :base0B "{color11}"
    :base0C "{color12}"
    :base0D "{color13}"
    :base0E "{color14}"
    :base0F "{color15}")
  "All colors for Base16 Ranbo are defined here.")

;; Define the theme
(deftheme base16-ranbo)

;; Add all the faces to the theme
(base16-theme-define 'base16-ranbo base16-ranbo-colors)

;; Mark the theme as provided
(provide-theme 'base16-ranbo)

(provide 'base16-ranbo-theme)

;;; base16-ranbo-theme.el ends here
